"""Add trace_id to price_history table

Revision ID: 0cebe4730269
Revises: e0ca0eceb449
Create Date: 2025-09-04 00:49:13.288213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cebe4730269'
down_revision = 'e0ca0eceb449'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('trace_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_price_history_trace_id'), 'price_history', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_trace_id'), table_name='price_history')
    op.drop_column('price_history', 'trace_id')
    # ### end Alembic commands ###