"""Add dropcase models for hotel price collections

Revision ID: ba9b9c008ca2
Revises: 0cebe4730269
Create Date: 2025-09-04 15:58:01.944817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9b9c008ca2'
down_revision = '0cebe4730269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dropcases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', 'DRAFT', name='dropcasestatus'), nullable=False),
    sa.Column('tracking_start_date', sa.Date(), nullable=False),
    sa.Column('tracking_end_date', sa.Date(), nullable=True),
    sa.Column('target_days', sa.Integer(), nullable=False),
    sa.Column('search_config', sa.JSON(), nullable=False),
    sa.Column('total_hotels', sa.Integer(), nullable=True),
    sa.Column('active_providers', sa.Integer(), nullable=True),
    sa.Column('last_price_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_daily_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_trend', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('target_days > 0', name='positive_target_days'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dropcase_creator', 'dropcases', ['created_by', 'status'], unique=False)
    op.create_index('idx_dropcase_status_date', 'dropcases', ['status', 'tracking_start_date'], unique=False)
    op.create_index(op.f('ix_dropcases_id'), 'dropcases', ['id'], unique=False)
    op.create_index(op.f('ix_dropcases_name'), 'dropcases', ['name'], unique=True)
    op.create_table('dropcase_daily_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dropcase_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('median_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weighted_avg_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_hotels_searched', sa.Integer(), nullable=True),
    sa.Column('total_hotels_available', sa.Integer(), nullable=True),
    sa.Column('total_providers_used', sa.Integer(), nullable=True),
    sa.Column('availability_rate', sa.Float(), nullable=True),
    sa.Column('price_std_deviation', sa.Float(), nullable=True),
    sa.Column('price_range', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_quartile_25', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_quartile_75', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_change_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_change_percent', sa.Float(), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('volatility_index', sa.Float(), nullable=True),
    sa.Column('data_completeness', sa.Float(), nullable=True),
    sa.Column('provider_coverage', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('dropcase_index_value', sa.Float(), nullable=True),
    sa.Column('index_change_percent', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('calculation_duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dropcase_id'], ['dropcases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dropcase_id', 'price_date', 'check_in_date', 'check_out_date', name='unique_dropcase_daily_price')
    )
    op.create_index('idx_daily_price_index', 'dropcase_daily_prices', ['price_date', 'dropcase_index_value'], unique=False)
    op.create_index('idx_dropcase_price_date', 'dropcase_daily_prices', ['dropcase_id', 'price_date'], unique=False)
    op.create_index('idx_dropcase_price_trend', 'dropcase_daily_prices', ['dropcase_id', 'trend_direction'], unique=False)
    op.create_index(op.f('ix_dropcase_daily_prices_id'), 'dropcase_daily_prices', ['id'], unique=False)
    op.create_index(op.f('ix_dropcase_daily_prices_price_date'), 'dropcase_daily_prices', ['price_date'], unique=False)
    op.create_table('dropcase_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dropcase_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.Enum('TRAVCLAN', 'BOOKING_COM', 'EXPEDIA', 'AGODA', 'HOTELS_COM', name='providertype'), nullable=False),
    sa.Column('provider_hotel_id', sa.String(length=255), nullable=False),
    sa.Column('hotel_name', sa.String(length=255), nullable=False),
    sa.Column('hotel_city', sa.String(length=100), nullable=True),
    sa.Column('hotel_country', sa.String(length=100), nullable=True),
    sa.Column('hotel_address', sa.Text(), nullable=True),
    sa.Column('hotel_stars', sa.Integer(), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_successful_fetch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_trend_7d', sa.String(length=20), nullable=True),
    sa.Column('price_trend_30d', sa.String(length=20), nullable=True),
    sa.Column('min_price_60d', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_price_60d', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_price_60d', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dropcase_id'], ['dropcases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dropcase_id', 'provider_name', 'provider_hotel_id', name='unique_dropcase_provider_hotel')
    )
    op.create_index('idx_dropcase_item_active', 'dropcase_items', ['dropcase_id', 'is_active'], unique=False)
    op.create_index('idx_dropcase_item_hotel', 'dropcase_items', ['provider_name', 'provider_hotel_id'], unique=False)
    op.create_index('idx_dropcase_item_provider', 'dropcase_items', ['dropcase_id', 'provider_name'], unique=False)
    op.create_index(op.f('ix_dropcase_items_hotel_name'), 'dropcase_items', ['hotel_name'], unique=False)
    op.create_index(op.f('ix_dropcase_items_id'), 'dropcase_items', ['id'], unique=False)
    op.create_index(op.f('ix_dropcase_items_provider_hotel_id'), 'dropcase_items', ['provider_hotel_id'], unique=False)
    op.create_index(op.f('ix_dropcase_items_provider_name'), 'dropcase_items', ['provider_name'], unique=False)
    op.create_table('dropcase_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dropcase_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notification_threshold', sa.Float(), nullable=True),
    sa.Column('notification_frequency', sa.String(length=20), nullable=True),
    sa.Column('last_notification_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_notifications_sent', sa.Integer(), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dropcase_id'], ['dropcases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dropcase_id', name='unique_user_dropcase_subscription')
    )
    op.create_index('idx_subscription_active', 'dropcase_subscriptions', ['dropcase_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_dropcase_subscriptions_id'), 'dropcase_subscriptions', ['id'], unique=False)
    op.create_table('dropcase_item_daily_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dropcase_item_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('occupancies', sa.JSON(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('median_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_rooms_found', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('availability_percentage', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('api_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('provider_raw_data', sa.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.Column('collection_successful', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['dropcase_item_id'], ['dropcase_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dropcase_item_id', 'price_date', 'check_in_date', 'check_out_date', name='unique_item_daily_price')
    )
    op.create_index('idx_item_price_checkin', 'dropcase_item_daily_prices', ['dropcase_item_id', 'check_in_date'], unique=False)
    op.create_index('idx_item_price_date', 'dropcase_item_daily_prices', ['dropcase_item_id', 'price_date'], unique=False)
    op.create_index('idx_price_collection_success', 'dropcase_item_daily_prices', ['price_date', 'collection_successful'], unique=False)
    op.create_index(op.f('ix_dropcase_item_daily_prices_id'), 'dropcase_item_daily_prices', ['id'], unique=False)
    op.create_index(op.f('ix_dropcase_item_daily_prices_price_date'), 'dropcase_item_daily_prices', ['price_date'], unique=False)
    op.create_index(op.f('ix_dropcase_item_daily_prices_trace_id'), 'dropcase_item_daily_prices', ['trace_id'], unique=False)
    op.add_column('bookings', sa.Column('hotel_name', sa.String(length=255), nullable=False))
    op.add_column('bookings', sa.Column('room_name', sa.String(length=255), nullable=False))
    op.add_column('bookings', sa.Column('hotel_city', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('hotel_country', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('external_hotel_id', sa.String(length=255), nullable=True))
    op.add_column('bookings', sa.Column('partner_name', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('occupancies', sa.JSON(), nullable=False))
    op.add_column('bookings', sa.Column('meal_plan', sa.Enum('ROOM_ONLY', 'BREAKFAST', 'HALF_BOARD', 'FULL_BOARD', 'ALL_INCLUSIVE', name='mealplan'), nullable=False))
    op.add_column('bookings', sa.Column('cancellation_policy', sa.Enum('FREE_CANCELLATION', 'NON_REFUNDABLE', 'PARTIAL_REFUND', 'CANCELLATION_FEE', 'FLEXIBLE', name='cancellationpolicy'), nullable=True))
    op.create_index(op.f('ix_bookings_cancellation_policy'), 'bookings', ['cancellation_policy'], unique=False)
    op.create_index(op.f('ix_bookings_external_hotel_id'), 'bookings', ['external_hotel_id'], unique=False)
    op.create_index(op.f('ix_bookings_hotel_city'), 'bookings', ['hotel_city'], unique=False)
    op.create_index(op.f('ix_bookings_hotel_name'), 'bookings', ['hotel_name'], unique=False)
    op.create_index(op.f('ix_bookings_meal_plan'), 'bookings', ['meal_plan'], unique=False)
    op.create_index(op.f('ix_bookings_room_name'), 'bookings', ['room_name'], unique=False)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'guests')
    op.drop_column('bookings', 'hotel_id')
    op.drop_column('bookings', 'room_id')
    op.add_column('price_history', sa.Column('external_hotel_id', sa.String(length=255), nullable=False))
    op.add_column('price_history', sa.Column('hotel_name', sa.String(length=255), nullable=False))
    op.add_column('price_history', sa.Column('room_name', sa.String(length=255), nullable=False))
    op.add_column('price_history', sa.Column('hotel_city', sa.String(length=100), nullable=True))
    op.add_column('price_history', sa.Column('occupancies', sa.JSON(), nullable=False))
    op.add_column('price_history', sa.Column('meal_plan', sa.Enum('ROOM_ONLY', 'BREAKFAST', 'HALF_BOARD', 'FULL_BOARD', 'ALL_INCLUSIVE', name='mealplan'), nullable=False))
    op.alter_column('price_history', 'cancellation_policy',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('FREE_CANCELLATION', 'NON_REFUNDABLE', 'PARTIAL_REFUND', 'CANCELLATION_FEE', 'FLEXIBLE', name='cancellationpolicy'),
               existing_nullable=True)
    op.drop_index(op.f('idx_hotel_price_date'), table_name='price_history')
    op.create_index('idx_hotel_price_date', 'price_history', ['external_hotel_id', 'price_date'], unique=False)
    op.drop_index(op.f('idx_price_lookup'), table_name='price_history')
    op.create_index('idx_price_lookup', 'price_history', ['external_hotel_id', 'room_name', 'check_in_date', 'check_out_date'], unique=False)
    op.drop_constraint(op.f('unique_price_record'), 'price_history', type_='unique')
    op.create_unique_constraint('unique_price_record', 'price_history', ['external_hotel_id', 'room_name', 'price_date', 'check_in_date', 'check_out_date', 'occupancies', 'meal_plan', 'cancellation_policy'])
    op.create_index(op.f('ix_price_history_cancellation_policy'), 'price_history', ['cancellation_policy'], unique=False)
    op.create_index(op.f('ix_price_history_external_hotel_id'), 'price_history', ['external_hotel_id'], unique=False)
    op.create_index(op.f('ix_price_history_hotel_city'), 'price_history', ['hotel_city'], unique=False)
    op.create_index(op.f('ix_price_history_hotel_name'), 'price_history', ['hotel_name'], unique=False)
    op.create_index(op.f('ix_price_history_meal_plan'), 'price_history', ['meal_plan'], unique=False)
    op.create_index(op.f('ix_price_history_room_name'), 'price_history', ['room_name'], unique=False)
    op.drop_constraint(None, 'price_history', type_='foreignkey')
    op.drop_constraint(None, 'price_history', type_='foreignkey')
    op.drop_column('price_history', 'hotel_id')
    op.drop_column('price_history', 'occupancy')
    op.drop_column('price_history', 'room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('room_id', sa.INTEGER(), nullable=False))
    op.add_column('price_history', sa.Column('occupancy', sa.INTEGER(), nullable=False))
    op.add_column('price_history', sa.Column('hotel_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'price_history', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'price_history', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_price_history_room_name'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_meal_plan'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_hotel_name'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_hotel_city'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_external_hotel_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_cancellation_policy'), table_name='price_history')
    op.drop_constraint('unique_price_record', 'price_history', type_='unique')
    op.create_unique_constraint(op.f('unique_price_record'), 'price_history', ['hotel_id', 'room_id', 'price_date', 'check_in_date', 'check_out_date', 'occupancy'])
    op.drop_index('idx_price_lookup', table_name='price_history')
    op.create_index(op.f('idx_price_lookup'), 'price_history', ['hotel_id', 'room_id', 'check_in_date', 'check_out_date'], unique=False)
    op.drop_index('idx_hotel_price_date', table_name='price_history')
    op.create_index(op.f('idx_hotel_price_date'), 'price_history', ['hotel_id', 'price_date'], unique=False)
    op.alter_column('price_history', 'cancellation_policy',
               existing_type=sa.Enum('FREE_CANCELLATION', 'NON_REFUNDABLE', 'PARTIAL_REFUND', 'CANCELLATION_FEE', 'FLEXIBLE', name='cancellationpolicy'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('price_history', 'meal_plan')
    op.drop_column('price_history', 'occupancies')
    op.drop_column('price_history', 'hotel_city')
    op.drop_column('price_history', 'room_name')
    op.drop_column('price_history', 'hotel_name')
    op.drop_column('price_history', 'external_hotel_id')
    op.add_column('bookings', sa.Column('room_id', sa.INTEGER(), nullable=False))
    op.add_column('bookings', sa.Column('hotel_id', sa.INTEGER(), nullable=False))
    op.add_column('bookings', sa.Column('guests', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'bookings', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bookings_room_name'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_meal_plan'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_hotel_name'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_hotel_city'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_external_hotel_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_cancellation_policy'), table_name='bookings')
    op.drop_column('bookings', 'cancellation_policy')
    op.drop_column('bookings', 'meal_plan')
    op.drop_column('bookings', 'occupancies')
    op.drop_column('bookings', 'partner_name')
    op.drop_column('bookings', 'external_hotel_id')
    op.drop_column('bookings', 'hotel_country')
    op.drop_column('bookings', 'hotel_city')
    op.drop_column('bookings', 'room_name')
    op.drop_column('bookings', 'hotel_name')
    op.drop_index(op.f('ix_dropcase_item_daily_prices_trace_id'), table_name='dropcase_item_daily_prices')
    op.drop_index(op.f('ix_dropcase_item_daily_prices_price_date'), table_name='dropcase_item_daily_prices')
    op.drop_index(op.f('ix_dropcase_item_daily_prices_id'), table_name='dropcase_item_daily_prices')
    op.drop_index('idx_price_collection_success', table_name='dropcase_item_daily_prices')
    op.drop_index('idx_item_price_date', table_name='dropcase_item_daily_prices')
    op.drop_index('idx_item_price_checkin', table_name='dropcase_item_daily_prices')
    op.drop_table('dropcase_item_daily_prices')
    op.drop_index(op.f('ix_dropcase_subscriptions_id'), table_name='dropcase_subscriptions')
    op.drop_index('idx_subscription_active', table_name='dropcase_subscriptions')
    op.drop_table('dropcase_subscriptions')
    op.drop_index(op.f('ix_dropcase_items_provider_name'), table_name='dropcase_items')
    op.drop_index(op.f('ix_dropcase_items_provider_hotel_id'), table_name='dropcase_items')
    op.drop_index(op.f('ix_dropcase_items_id'), table_name='dropcase_items')
    op.drop_index(op.f('ix_dropcase_items_hotel_name'), table_name='dropcase_items')
    op.drop_index('idx_dropcase_item_provider', table_name='dropcase_items')
    op.drop_index('idx_dropcase_item_hotel', table_name='dropcase_items')
    op.drop_index('idx_dropcase_item_active', table_name='dropcase_items')
    op.drop_table('dropcase_items')
    op.drop_index(op.f('ix_dropcase_daily_prices_price_date'), table_name='dropcase_daily_prices')
    op.drop_index(op.f('ix_dropcase_daily_prices_id'), table_name='dropcase_daily_prices')
    op.drop_index('idx_dropcase_price_trend', table_name='dropcase_daily_prices')
    op.drop_index('idx_dropcase_price_date', table_name='dropcase_daily_prices')
    op.drop_index('idx_daily_price_index', table_name='dropcase_daily_prices')
    op.drop_table('dropcase_daily_prices')
    op.drop_index(op.f('ix_dropcases_name'), table_name='dropcases')
    op.drop_index(op.f('ix_dropcases_id'), table_name='dropcases')
    op.drop_index('idx_dropcase_status_date', table_name='dropcases')
    op.drop_index('idx_dropcase_creator', table_name='dropcases')
    op.drop_table('dropcases')
    # ### end Alembic commands ###