"""Add hotel booking and price tracking models

Revision ID: e0ca0eceb449
Revises: 176e19d89158
Create Date: 2025-09-04 00:15:12.511752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ca0eceb449'
down_revision = '176e19d89158'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('partner_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_bookable', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('api_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    op.create_index(op.f('ix_hotels_country'), 'hotels', ['country'], unique=False)
    op.create_index(op.f('ix_hotels_external_id'), 'hotels', ['external_id'], unique=True)
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_index(op.f('ix_hotels_name'), 'hotels', ['name'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('bed_type', sa.String(length=100), nullable=True),
    sa.Column('room_size_sqm', sa.Float(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_bookable', sa.Boolean(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('api_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_external_id'), 'rooms', ['external_id'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('room_preferences', sa.JSON(), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('initial_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('booking_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', 'BOOKED', name='bookingstatus'), nullable=False),
    sa.Column('notification_status', sa.Enum('ENABLED', 'DISABLED', 'PAUSED', name='notificationstatus'), nullable=False),
    sa.Column('price_drop_threshold_percent', sa.Float(), nullable=True),
    sa.Column('price_drop_threshold_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_notification_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_frequency_hours', sa.Integer(), nullable=True),
    sa.Column('external_booking_reference', sa.String(length=255), nullable=True),
    sa.Column('booking_platform', sa.String(length=100), nullable=True),
    sa.Column('actual_booking_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_booking_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('check_out_date > check_in_date', name='valid_date_range'),
    sa.CheckConstraint('guests > 0', name='positive_guests'),
    sa.CheckConstraint('nights > 0', name='positive_nights'),
    sa.CheckConstraint('price_drop_threshold_percent >= 0', name='valid_threshold_percent'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_check_in_date'), 'bookings', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_bookings_check_out_date'), 'bookings', ['check_out_date'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('occupancy', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(length=100), nullable=False),
    sa.Column('external_rate_id', sa.String(length=255), nullable=True),
    sa.Column('rate_name', sa.String(length=255), nullable=True),
    sa.Column('cancellation_policy', sa.String(length=255), nullable=True),
    sa.Column('payment_policy', sa.String(length=255), nullable=True),
    sa.Column('booking_conditions', sa.JSON(), nullable=True),
    sa.Column('price_changed', sa.Boolean(), nullable=True),
    sa.Column('previous_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_change_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_change_percent', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('api_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('api_raw_data', sa.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'room_id', 'price_date', 'check_in_date', 'check_out_date', 'occupancy', name='unique_price_record')
    )
    op.create_index('idx_hotel_price_date', 'price_history', ['hotel_id', 'price_date'], unique=False)
    op.create_index('idx_price_collection_date', 'price_history', ['collected_at'], unique=False)
    op.create_index('idx_price_date_range', 'price_history', ['price_date', 'check_in_date'], unique=False)
    op.create_index('idx_price_lookup', 'price_history', ['hotel_id', 'room_id', 'check_in_date', 'check_out_date'], unique=False)
    op.create_index(op.f('ix_price_history_check_in_date'), 'price_history', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_price_history_check_out_date'), 'price_history', ['check_out_date'], unique=False)
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    op.create_index(op.f('ix_price_history_price_date'), 'price_history', ['price_date'], unique=False)
    op.create_table('price_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('median_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_trend', sa.String(length=20), nullable=True),
    sa.Column('trend_strength', sa.Float(), nullable=True),
    sa.Column('price_volatility', sa.Float(), nullable=True),
    sa.Column('price_range', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price_points', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'room_id', 'check_in_date', 'check_out_date', name='unique_price_stats')
    )
    op.create_index('idx_stats_lookup', 'price_statistics', ['hotel_id', 'room_id', 'check_in_date'], unique=False)
    op.create_index(op.f('ix_price_statistics_check_in_date'), 'price_statistics', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_price_statistics_check_out_date'), 'price_statistics', ['check_out_date'], unique=False)
    op.create_index(op.f('ix_price_statistics_id'), 'price_statistics', ['id'], unique=False)
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_difference', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percentage_change', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('alert_data', sa.JSON(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_method', sa.String(length=50), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_id'), 'price_alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_alerts_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_price_statistics_id'), table_name='price_statistics')
    op.drop_index(op.f('ix_price_statistics_check_out_date'), table_name='price_statistics')
    op.drop_index(op.f('ix_price_statistics_check_in_date'), table_name='price_statistics')
    op.drop_index('idx_stats_lookup', table_name='price_statistics')
    op.drop_table('price_statistics')
    op.drop_index(op.f('ix_price_history_price_date'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_check_out_date'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_check_in_date'), table_name='price_history')
    op.drop_index('idx_price_lookup', table_name='price_history')
    op.drop_index('idx_price_date_range', table_name='price_history')
    op.drop_index('idx_price_collection_date', table_name='price_history')
    op.drop_index('idx_hotel_price_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_check_out_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_check_in_date'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_external_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_hotels_name'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_external_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_country'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_table('hotels')
    # ### end Alembic commands ###