from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS "countries" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "iso_code_2" VARCHAR(2) NOT NULL UNIQUE,
    "iso_code_3" VARCHAR(3) NOT NULL UNIQUE,
    "numeric_code" VARCHAR(3),
    "name" VARCHAR(100) NOT NULL,
    "official_name" VARCHAR(255),
    "common_name" VARCHAR(100),
    "continent" VARCHAR(50),
    "region" VARCHAR(100),
    "sub_region" VARCHAR(100),
    "currency_code" VARCHAR(3),
    "currency_name" VARCHAR(50),
    "languages" JSON,
    "capital_city" VARCHAR(100),
    "latitude" REAL,
    "longitude" REAL,
    "calling_code" VARCHAR(10),
    "timezone_info" JSON,
    "popular_destinations" JSON,
    "is_active" INT NOT NULL DEFAULT 1,
    "is_popular" INT NOT NULL DEFAULT 0,
    "travel_restrictions" JSON,
    "external_ids" JSON,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "destinations" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "display_name" VARCHAR(150),
    "local_name" VARCHAR(100),
    "destination_type" VARCHAR(50) NOT NULL DEFAULT 'city',
    "state_province" VARCHAR(100),
    "administrative_area" VARCHAR(100),
    "latitude" REAL NOT NULL,
    "longitude" REAL NOT NULL,
    "description" TEXT,
    "population" INT,
    "area_km2" REAL,
    "elevation_m" INT,
    "tourist_rating" REAL,
    "best_visit_months" JSON,
    "climate_type" VARCHAR(50),
    "famous_attractions" JSON,
    "timezone" VARCHAR(50),
    "airport_codes" JSON,
    "common_languages" JSON,
    "external_ids" JSON,
    "google_place_id" VARCHAR(255),
    "is_active" INT NOT NULL DEFAULT 1,
    "is_popular" INT NOT NULL DEFAULT 0,
    "is_capital" INT NOT NULL DEFAULT 0,
    "priority_score" INT NOT NULL DEFAULT 0,
    "slug" VARCHAR(100) UNIQUE,
    "meta_description" TEXT,
    "keywords" JSON,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "country_id" INT NOT NULL REFERENCES "countries" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "airports" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "iata_code" VARCHAR(3) NOT NULL UNIQUE,
    "icao_code" VARCHAR(4) UNIQUE,
    "faa_code" VARCHAR(4),
    "name" VARCHAR(255) NOT NULL,
    "official_name" VARCHAR(300),
    "common_name" VARCHAR(200),
    "local_name" VARCHAR(255),
    "city" VARCHAR(100) NOT NULL,
    "state_province" VARCHAR(100),
    "latitude" REAL NOT NULL,
    "longitude" REAL NOT NULL,
    "elevation_ft" INT,
    "elevation_m" INT,
    "airport_type" VARCHAR(13) NOT NULL DEFAULT 'international' /* INTERNATIONAL: international\nDOMESTIC: domestic\nREGIONAL: regional\nPRIVATE: private\nCARGO: cargo\nMILITARY: military */,
    "airport_size" VARCHAR(8) NOT NULL DEFAULT 'medium' /* LARGE: large\nMEDIUM: medium\nSMALL: small\nREGIONAL: regional */,
    "timezone" VARCHAR(50) NOT NULL,
    "utc_offset" VARCHAR(10),
    "runway_count" INT,
    "terminal_count" INT,
    "annual_passengers" INT,
    "cargo_capacity_tons" INT,
    "facilities" JSON,
    "airlines" JSON,
    "car_rental_companies" JSON,
    "ground_transport" JSON,
    "distance_to_city_km" REAL,
    "drive_time_minutes" INT,
    "external_ids" JSON,
    "google_place_id" VARCHAR(255),
    "is_hub" INT NOT NULL DEFAULT 0,
    "is_international" INT NOT NULL DEFAULT 1,
    "passenger_rating" REAL,
    "on_time_performance" REAL,
    "is_active" INT NOT NULL DEFAULT 1,
    "is_operational" INT NOT NULL DEFAULT 1,
    "operational_notes" TEXT,
    "slug" VARCHAR(100) UNIQUE,
    "description" TEXT,
    "meta_description" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_verified" TIMESTAMP,
    "country_id" INT NOT NULL REFERENCES "countries" ("id") ON DELETE CASCADE,
    "destination_id" INT REFERENCES "destinations" ("id") ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS "areas" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "display_name" VARCHAR(150),
    "local_name" VARCHAR(100),
    "area_type" VARCHAR(50) NOT NULL DEFAULT 'district',
    "area_level" INT NOT NULL DEFAULT 1,
    "latitude" REAL,
    "longitude" REAL,
    "boundary_coordinates" JSON,
    "description" TEXT,
    "characteristics" JSON,
    "popular_for" JSON,
    "transport_hubs" JSON,
    "walkability_score" REAL,
    "hotel_density" VARCHAR(20),
    "attraction_count" INT NOT NULL DEFAULT 0,
    "restaurant_count" INT NOT NULL DEFAULT 0,
    "avg_hotel_price_range" VARCHAR(20),
    "external_ids" JSON,
    "google_place_id" VARCHAR(255),
    "is_active" INT NOT NULL DEFAULT 1,
    "is_popular" INT NOT NULL DEFAULT 0,
    "priority_score" INT NOT NULL DEFAULT 0,
    "slug" VARCHAR(100),
    "meta_description" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "country_id" INT NOT NULL REFERENCES "countries" ("id") ON DELETE CASCADE,
    "destination_id" INT NOT NULL REFERENCES "destinations" ("id") ON DELETE CASCADE,
    "parent_area_id" INT REFERENCES "areas" ("id") ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS "flights" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "flight_number" VARCHAR(20) NOT NULL,
    "airline_code" VARCHAR(3) NOT NULL,
    "airline_name" VARCHAR(100) NOT NULL,
    "aircraft_type" VARCHAR(11) /* NARROW_BODY: narrow_body\nWIDE_BODY: wide_body\nREGIONAL: regional\nTURBOPROP: turboprop\nPRIVATE_JET: private_jet\nOTHER: other */,
    "aircraft_code" VARCHAR(10),
    "flight_type" VARCHAR(9) NOT NULL DEFAULT 'scheduled' /* SCHEDULED: scheduled\nCHARTER: charter\nCARGO: cargo\nPRIVATE: private */,
    "departure_time_utc" TIMESTAMP NOT NULL,
    "arrival_time_utc" TIMESTAMP NOT NULL,
    "departure_time_local" TIMESTAMP NOT NULL,
    "arrival_time_local" TIMESTAMP NOT NULL,
    "duration_minutes" INT NOT NULL,
    "distance_km" INT,
    "distance_miles" INT,
    "operates_on" JSON,
    "valid_from" DATE,
    "valid_to" DATE,
    "seasonal_info" JSON,
    "cabin_classes" JSON NOT NULL,
    "total_seats" INT,
    "seat_configuration" JSON,
    "services" JSON,
    "baggage_policy" JSON,
    "meal_service" JSON,
    "external_ids" JSON,
    "external_flight_data" JSON,
    "typical_price_ranges" JSON,
    "price_currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "status" VARCHAR(9) NOT NULL DEFAULT 'active' /* SCHEDULED: scheduled\nACTIVE: active\nCANCELLED: cancelled\nDELAYED: delayed\nCOMPLETED: completed */,
    "is_bookable" INT NOT NULL DEFAULT 1,
    "is_codeshare" INT NOT NULL DEFAULT 0,
    "operating_airline" VARCHAR(100),
    "is_popular_route" INT NOT NULL DEFAULT 0,
    "route_popularity_score" INT NOT NULL DEFAULT 0,
    "on_time_performance" REAL,
    "last_price_update" TIMESTAMP,
    "data_source" VARCHAR(100),
    "api_last_updated" TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "arrival_airport_id" INT NOT NULL REFERENCES "airports" ("id") ON DELETE CASCADE,
    "departure_airport_id" INT NOT NULL REFERENCES "airports" ("id") ON DELETE CASCADE,
    CONSTRAINT "uid_flights_flight__3055f8" UNIQUE ("flight_number", "airline_code", "departure_time_utc")
);
CREATE TABLE IF NOT EXISTS "hotels" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "external_id" VARCHAR(255) NOT NULL UNIQUE,
    "partner_name" VARCHAR(100) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "display_name" VARCHAR(300),
    "brand_name" VARCHAR(100),
    "description" TEXT,
    "short_description" VARCHAR(500),
    "address" TEXT NOT NULL,
    "city" VARCHAR(100) NOT NULL,
    "postal_code" VARCHAR(20),
    "latitude" REAL,
    "longitude" REAL,
    "hotel_type" VARCHAR(10) NOT NULL DEFAULT 'hotel' /* HOTEL: hotel\nRESORT: resort\nAPARTHOTEL: aparthotel\nHOSTEL: hostel\nGUESTHOUSE: guesthouse\nVILLA: villa\nAPARTMENT: apartment\nMOTEL: motel\nBOUTIQUE: boutique\nLUXURY: luxury\nBUSINESS: business */,
    "hotel_chain" VARCHAR(12) NOT NULL DEFAULT 'independent' /* INDEPENDENT: independent\nMARRIOTT: marriott\nHILTON: hilton\nIHG: ihg\nHYATT: hyatt\nACCOR: accor\nCHOICE: choice\nWYNDHAM: wyndham\nBEST_WESTERN: best_western\nOTHER: other */,
    "star_rating" INT,
    "official_rating" VARCHAR(20),
    "guest_rating" REAL,
    "guest_rating_count" INT NOT NULL DEFAULT 0,
    "phone_number" VARCHAR(50),
    "email" VARCHAR(255),
    "website_url" VARCHAR(500),
    "year_built" INT,
    "year_renovated" INT,
    "total_rooms" INT,
    "total_floors" INT,
    "check_in_time" VARCHAR(10),
    "check_out_time" VARCHAR(10),
    "amenities" JSON,
    "images" JSON,
    "facilities" JSON,
    "accessibility_features" JSON,
    "pet_policy" JSON,
    "children_policy" JSON,
    "is_active" INT NOT NULL DEFAULT 1,
    "is_bookable" INT NOT NULL DEFAULT 1,
    "is_featured" INT NOT NULL DEFAULT 0,
    "is_popular" INT NOT NULL DEFAULT 0,
    "business_center" INT NOT NULL DEFAULT 0,
    "meeting_rooms" INT NOT NULL DEFAULT 0,
    "conference_facilities" JSON,
    "sustainability_certifications" JSON,
    "sustainability_score" REAL,
    "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "typical_price_range" VARCHAR(20),
    "price_level" INT,
    "api_last_updated" TIMESTAMP,
    "api_data" JSON,
    "external_ids" JSON,
    "slug" VARCHAR(200) UNIQUE,
    "meta_title" VARCHAR(200),
    "meta_description" TEXT,
    "keywords" JSON,
    "view_count" INT NOT NULL DEFAULT 0,
    "booking_count" INT NOT NULL DEFAULT 0,
    "popularity_score" REAL NOT NULL DEFAULT 0,
    "last_booked" TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_verified" TIMESTAMP,
    "area_id" INT REFERENCES "areas" ("id") ON DELETE SET NULL,
    "country_id" INT NOT NULL REFERENCES "countries" ("id") ON DELETE CASCADE,
    "destination_id" INT NOT NULL REFERENCES "destinations" ("id") ON DELETE CASCADE,
    CONSTRAINT "uid_hotels_externa_6183a7" UNIQUE ("external_id", "partner_name")
);
CREATE TABLE IF NOT EXISTS "rooms" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "external_id" VARCHAR(255) NOT NULL,
    "external_ids" JSON,
    "name" VARCHAR(255) NOT NULL,
    "display_name" VARCHAR(300),
    "description" TEXT,
    "short_description" VARCHAR(500),
    "room_type" VARCHAR(12) NOT NULL DEFAULT 'standard' /* STANDARD: standard\nDELUXE: deluxe\nSUPERIOR: superior\nSUITE: suite\nJUNIOR_SUITE: junior_suite\nPRESIDENTIAL: presidential\nFAMILY: family\nCONNECTING: connecting\nACCESSIBLE: accessible\nSTUDIO: studio\nAPARTMENT: apartment\nVILLA: villa */,
    "room_category" VARCHAR(100),
    "room_code" VARCHAR(50),
    "max_occupancy" INT NOT NULL DEFAULT 2,
    "max_adults" INT,
    "max_children" INT,
    "bed_configuration" JSON,
    "primary_bed_type" VARCHAR(10) /* SINGLE: single\nTWIN: twin\nDOUBLE: double\nQUEEN: queen\nKING: king\nSOFA_BED: sofa_bed\nBUNK_BED: bunk_bed\nMURPHY_BED: murphy_bed */,
    "room_size_sqm" REAL,
    "room_size_sqft" REAL,
    "floor_number" INT,
    "room_numbers" JSON,
    "view_type" VARCHAR(100),
    "balcony_terrace" INT NOT NULL DEFAULT 0,
    "floor_level" VARCHAR(50),
    "amenities" JSON,
    "bathroom_features" JSON,
    "technology_features" JSON,
    "comfort_features" JSON,
    "kitchen_facilities" JSON,
    "dining_area" INT NOT NULL DEFAULT 0,
    "accessibility_features" JSON,
    "is_accessible" INT NOT NULL DEFAULT 0,
    "images" JSON,
    "virtual_tour_url" VARCHAR(500),
    "is_active" INT NOT NULL DEFAULT 1,
    "is_bookable" INT NOT NULL DEFAULT 1,
    "is_featured" INT NOT NULL DEFAULT 0,
    "base_price" REAL,
    "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "total_rooms" INT,
    "room_inventory_code" VARCHAR(100),
    "api_last_updated" TIMESTAMP,
    "api_data" JSON,
    "booking_count" INT NOT NULL DEFAULT 0,
    "popularity_score" REAL NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_verified" TIMESTAMP,
    "hotel_id" INT NOT NULL REFERENCES "hotels" ("id") ON DELETE CASCADE,
    CONSTRAINT "uid_rooms_hotel_i_f954e8" UNIQUE ("hotel_id", "external_id")
);
CREATE TABLE IF NOT EXISTS "universal_price_history" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "trackable_type" VARCHAR(10) NOT NULL /* HOTEL_ROOM: hotel_room\nFLIGHT: flight\nPACKAGE: package\nACTIVITY: activity */,
    "trackable_id" INT NOT NULL,
    "secondary_trackable_type" VARCHAR(50),
    "secondary_trackable_id" INT,
    "price_date" DATE NOT NULL,
    "search_date" DATE NOT NULL,
    "search_end_date" DATE,
    "price" VARCHAR(40) NOT NULL,
    "base_price" VARCHAR(40),
    "taxes_fees" VARCHAR(40),
    "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "is_available" INT NOT NULL DEFAULT 1,
    "availability_count" INT,
    "booking_conditions" JSON,
    "search_criteria" JSON NOT NULL,
    "rate_plan_name" VARCHAR(200),
    "rate_plan_code" VARCHAR(100),
    "restrictions" JSON,
    "cancellation_policy" VARCHAR(100),
    "previous_price" VARCHAR(40),
    "price_change_amount" VARCHAR(40),
    "price_change_percent" REAL,
    "is_price_drop" INT,
    "is_price_increase" INT,
    "data_source" VARCHAR(100) NOT NULL,
    "external_rate_id" VARCHAR(255),
    "api_response_time_ms" INT,
    "trace_id" VARCHAR(255),
    "confidence_score" REAL,
    "data_freshness_minutes" INT,
    "validation_errors" JSON,
    "raw_api_response" JSON,
    "recorded_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "destination_country_id" INT REFERENCES "countries" ("id") ON DELETE SET NULL,
    "destination_destination_id" INT REFERENCES "destinations" ("id") ON DELETE SET NULL,
    "origin_country_id" INT REFERENCES "countries" ("id") ON DELETE SET NULL,
    "origin_destination_id" INT REFERENCES "destinations" ("id") ON DELETE SET NULL,
    CONSTRAINT "uid_universal_p_trackab_a4d752" UNIQUE ("trackable_type", "trackable_id", "secondary_trackable_id", "price_date", "search_date", "search_end_date", "data_source")
);
CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "hashed_password" VARCHAR(255) NOT NULL,
    "full_name" VARCHAR(100),
    "is_active" INT NOT NULL DEFAULT 1,
    "is_superuser" INT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "clusters" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "display_name" VARCHAR(255),
    "description" TEXT,
    "cluster_type" VARCHAR(12) NOT NULL DEFAULT 'geographic' /* GEOGRAPHIC: geographic\nTHEMATIC: thematic\nSEASONAL: seasonal\nPRICE_TIER: price_tier\nTRAVEL_STYLE: travel_style\nCUSTOM: custom */,
    "category" VARCHAR(100),
    "subcategory" VARCHAR(100),
    "is_system_cluster" INT NOT NULL DEFAULT 0,
    "is_dynamic" INT NOT NULL DEFAULT 0,
    "update_rules" JSON,
    "icon_name" VARCHAR(50),
    "color_code" VARCHAR(7),
    "sort_order" INT NOT NULL DEFAULT 0,
    "bounding_box" JSON,
    "center_latitude" VARCHAR(20),
    "center_longitude" VARCHAR(20),
    "total_items" INT NOT NULL DEFAULT 0,
    "item_type_counts" JSON,
    "popularity_score" INT NOT NULL DEFAULT 0,
    "external_ids" JSON,
    "tags" JSON,
    "is_active" INT NOT NULL DEFAULT 1,
    "is_public" INT NOT NULL DEFAULT 1,
    "is_featured" INT NOT NULL DEFAULT 0,
    "slug" VARCHAR(100) UNIQUE,
    "meta_title" VARCHAR(200),
    "meta_description" TEXT,
    "keywords" JSON,
    "is_shared" INT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_recalculated" TIMESTAMP,
    "created_by_user_id" INT REFERENCES "users" ("id") ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS "cluster_items" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "item_type" VARCHAR(12) NOT NULL /* COUNTRY: country\nDESTINATION: destination\nAREA: area\nAIRPORT: airport\nHOTEL: hotel\nFLIGHT_ROUTE: flight_route */,
    "item_id" INT NOT NULL,
    "item_name" VARCHAR(255),
    "item_display_name" VARCHAR(255),
    "item_description" TEXT,
    "latitude" VARCHAR(20),
    "longitude" VARCHAR(20),
    "weight" INT NOT NULL DEFAULT 1,
    "sort_order" INT NOT NULL DEFAULT 0,
    "is_primary" INT NOT NULL DEFAULT 0,
    "custom_attributes" JSON,
    "inclusion_reason" VARCHAR(200),
    "auto_added" INT NOT NULL DEFAULT 0,
    "rule_criteria" JSON,
    "is_active" INT NOT NULL DEFAULT 1,
    "is_validated" INT NOT NULL DEFAULT 1,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_validated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "cluster_id" INT NOT NULL REFERENCES "clusters" ("id") ON DELETE CASCADE,
    "country_id" INT REFERENCES "countries" ("id") ON DELETE CASCADE,
    "destination_id" INT REFERENCES "destinations" ("id") ON DELETE CASCADE,
    CONSTRAINT "uid_cluster_ite_cluster_ff4da3" UNIQUE ("cluster_id", "item_type", "item_id")
);
CREATE TABLE IF NOT EXISTS "refresh_tokens" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "token" VARCHAR(255) NOT NULL UNIQUE,
    "expires_at" TIMESTAMP NOT NULL,
    "is_revoked" INT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" INT NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "trackers" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "tracker_type" VARCHAR(13) NOT NULL DEFAULT 'hotel_search' /* HOTEL_SEARCH: hotel_search\nFLIGHT_SEARCH: flight_search\nMIXED_SEARCH: mixed_search\nCUSTOM_LIST: custom_list */,
    "start_date" DATE NOT NULL,
    "end_date" DATE NOT NULL,
    "flexible_dates" INT NOT NULL DEFAULT 0,
    "date_flexibility_days" INT,
    "trackable_items" JSON NOT NULL,
    "search_criteria" JSON NOT NULL,
    "filters" JSON,
    "preferences" JSON,
    "exclusions" JSON,
    "price_range_min" VARCHAR(40),
    "price_range_max" VARCHAR(40),
    "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "alert_triggers" JSON NOT NULL,
    "price_drop_threshold_percent" REAL DEFAULT 10,
    "price_drop_threshold_amount" VARCHAR(40),
    "price_increase_threshold_percent" REAL,
    "tracking_frequency" VARCHAR(8) NOT NULL DEFAULT 'medium' /* REALTIME: realtime\nHIGH: high\nMEDIUM: medium\nLOW: low\nDAILY: daily\nCUSTOM: custom */,
    "custom_interval_minutes" INT,
    "tracking_schedule" JSON,
    "timezone" VARCHAR(50) NOT NULL DEFAULT 'UTC',
    "status" VARCHAR(9) NOT NULL DEFAULT 'active' /* ACTIVE: active\nPAUSED: paused\nSTOPPED: stopped\nEXPIRED: expired\nERROR: error\nCOMPLETED: completed */,
    "is_shared" INT NOT NULL DEFAULT 0,
    "is_template" INT NOT NULL DEFAULT 0,
    "last_run_at" TIMESTAMP,
    "next_run_at" TIMESTAMP,
    "total_runs" INT NOT NULL DEFAULT 0,
    "successful_runs" INT NOT NULL DEFAULT 0,
    "failed_runs" INT NOT NULL DEFAULT 0,
    "last_error" TEXT,
    "total_items_tracked" INT NOT NULL DEFAULT 0,
    "active_items_tracked" INT NOT NULL DEFAULT 0,
    "price_alerts_sent" INT NOT NULL DEFAULT 0,
    "best_price_found" VARCHAR(40),
    "average_price_found" VARCHAR(40),
    "last_results_summary" JSON,
    "average_execution_time_seconds" REAL,
    "api_calls_per_run" INT,
    "data_quality_score" REAL,
    "notification_settings" JSON,
    "email_notifications" INT NOT NULL DEFAULT 1,
    "push_notifications" INT NOT NULL DEFAULT 1,
    "sms_notifications" INT NOT NULL DEFAULT 0,
    "notification_frequency_limit_hours" INT NOT NULL DEFAULT 4,
    "external_tracker_ids" JSON,
    "webhook_url" VARCHAR(500),
    "api_integrations" JSON,
    "monthly_api_call_limit" INT,
    "monthly_api_calls_used" INT NOT NULL DEFAULT 0,
    "estimated_monthly_cost" VARCHAR(40),
    "auto_pause_on_no_results" INT NOT NULL DEFAULT 0,
    "auto_stop_after_days" INT,
    "auto_adjust_frequency" INT NOT NULL DEFAULT 0,
    "tags" JSON,
    "priority" INT NOT NULL DEFAULT 0,
    "folder" VARCHAR(100),
    "view_count" INT NOT NULL DEFAULT 0,
    "last_viewed" TIMESTAMP,
    "insights" JSON,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "starts_at" TIMESTAMP,
    "expires_at" TIMESTAMP,
    "area_id" INT REFERENCES "areas" ("id") ON DELETE SET NULL,
    "cluster_id" INT REFERENCES "clusters" ("id") ON DELETE SET NULL,
    "country_id" INT REFERENCES "countries" ("id") ON DELETE CASCADE,
    "created_by_user_id" INT REFERENCES "users" ("id") ON DELETE SET NULL,
    "destination_id" INT REFERENCES "destinations" ("id") ON DELETE CASCADE,
    "origin_country_id" INT REFERENCES "countries" ("id") ON DELETE CASCADE,
    "origin_destination_id" INT REFERENCES "destinations" ("id") ON DELETE CASCADE,
    "user_id" INT NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "tracker_alerts" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "alert_type" VARCHAR(50) NOT NULL,
    "alert_title" VARCHAR(255) NOT NULL,
    "alert_message" TEXT NOT NULL,
    "alert_data" JSON,
    "trigger_run_id" VARCHAR(100),
    "trigger_data" JSON,
    "affected_items" JSON,
    "old_price" VARCHAR(40),
    "new_price" VARCHAR(40),
    "price_change_percent" REAL,
    "delivery_channels" JSON NOT NULL,
    "delivery_status" JSON,
    "sent_at" TIMESTAMP,
    "delivered_at" TIMESTAMP,
    "is_read" INT NOT NULL DEFAULT 0,
    "read_at" TIMESTAMP,
    "user_action" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMP,
    "tracker_id" INT NOT NULL REFERENCES "trackers" ("id") ON DELETE CASCADE,
    "user_id" INT NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "tracker_results" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "run_id" VARCHAR(100) NOT NULL,
    "execution_start" TIMESTAMP NOT NULL,
    "execution_end" TIMESTAMP NOT NULL,
    "execution_time_seconds" REAL NOT NULL,
    "success" INT NOT NULL DEFAULT 0,
    "error_message" TEXT,
    "items_found" INT NOT NULL DEFAULT 0,
    "available_items" INT NOT NULL DEFAULT 0,
    "price_changes_detected" INT NOT NULL DEFAULT 0,
    "lowest_price" VARCHAR(40),
    "highest_price" VARCHAR(40),
    "average_price" VARCHAR(40),
    "median_price" VARCHAR(40),
    "api_calls_made" INT NOT NULL DEFAULT 0,
    "api_errors" INT NOT NULL DEFAULT 0,
    "data_sources_used" JSON,
    "results_data" JSON,
    "insights" JSON,
    "recommendations" JSON,
    "data_quality_score" REAL,
    "data_completeness" REAL,
    "validation_warnings" JSON,
    "alerts_triggered" INT NOT NULL DEFAULT 0,
    "alert_types" JSON,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "tracker_id" INT NOT NULL REFERENCES "trackers" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "universal_bookings" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "bookable_type" VARCHAR(9) NOT NULL /* HOTEL: hotel\nFLIGHT: flight\nPACKAGE: package\nACTIVITY: activity\nTRANSFER: transfer\nINSURANCE: insurance */,
    "bookable_id" INT NOT NULL,
    "secondary_bookable_type" VARCHAR(50),
    "secondary_bookable_id" INT,
    "booking_reference" VARCHAR(100) NOT NULL UNIQUE,
    "external_booking_reference" VARCHAR(255),
    "partner_name" VARCHAR(100),
    "travel_start_date" DATE NOT NULL,
    "travel_end_date" DATE,
    "travel_duration_days" INT,
    "travelers" JSON NOT NULL,
    "total_travelers" INT NOT NULL DEFAULT 1,
    "preferences" JSON,
    "special_requests" TEXT,
    "booking_conditions" JSON,
    "base_price" VARCHAR(40),
    "current_price" VARCHAR(40),
    "target_price" VARCHAR(40),
    "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "price_drop_threshold_percent" REAL DEFAULT 5,
    "price_drop_threshold_amount" VARCHAR(40),
    "price_increase_alert" INT NOT NULL DEFAULT 0,
    "booking_name" VARCHAR(255),
    "booking_notes" TEXT,
    "tags" JSON,
    "status" VARCHAR(9) NOT NULL DEFAULT 'active' /* DRAFT: draft\nACTIVE: active\nCANCELLED: cancelled\nEXPIRED: expired\nBOOKED: booked\nCOMPLETED: completed */,
    "notification_status" VARCHAR(17) NOT NULL DEFAULT 'enabled' /* ENABLED: enabled\nDISABLED: disabled\nPAUSED: paused\nFREQUENCY_LIMITED: frequency_limited */,
    "payment_status" VARCHAR(14) /* PENDING: pending\nPAID: paid\nPARTIALLY_PAID: partially_paid\nREFUNDED: refunded\nCANCELLED: cancelled */,
    "last_notification_sent" TIMESTAMP,
    "notification_frequency_hours" INT NOT NULL DEFAULT 24,
    "email_notifications" INT NOT NULL DEFAULT 1,
    "push_notifications" INT NOT NULL DEFAULT 1,
    "sms_notifications" INT NOT NULL DEFAULT 0,
    "actual_booking_date" TIMESTAMP,
    "actual_booking_price" VARCHAR(40),
    "booking_platform" VARCHAR(100),
    "confirmation_number" VARCHAR(255),
    "external_data" JSON,
    "last_price_check" TIMESTAMP,
    "price_check_frequency_minutes" INT NOT NULL DEFAULT 60,
    "price_alerts_sent" INT NOT NULL DEFAULT 0,
    "times_viewed" INT NOT NULL DEFAULT 0,
    "last_viewed" TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMP,
    "destination_country_id" INT REFERENCES "countries" ("id") ON DELETE SET NULL,
    "destination_destination_id" INT REFERENCES "destinations" ("id") ON DELETE SET NULL,
    "origin_country_id" INT REFERENCES "countries" ("id") ON DELETE SET NULL,
    "origin_destination_id" INT REFERENCES "destinations" ("id") ON DELETE SET NULL,
    "user_id" INT NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "universal_price_alerts" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "alert_type" VARCHAR(50) NOT NULL,
    "trigger_condition" JSON NOT NULL,
    "old_price" VARCHAR(40),
    "new_price" VARCHAR(40),
    "price_difference" VARCHAR(40),
    "percentage_change" REAL,
    "alert_title" VARCHAR(255) NOT NULL,
    "alert_message" TEXT NOT NULL,
    "alert_data" JSON,
    "delivery_channels" JSON NOT NULL,
    "delivery_status" JSON,
    "sent_at" TIMESTAMP,
    "delivered_at" TIMESTAMP,
    "is_read" INT NOT NULL DEFAULT 0,
    "read_at" TIMESTAMP,
    "user_action" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMP,
    "booking_id" INT NOT NULL REFERENCES "universal_bookings" ("id") ON DELETE CASCADE,
    "user_id" INT NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(100) NOT NULL,
    "content" JSON NOT NULL
);"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """
